# >>=====================================<<
# åç§°: MihomoProLite
# åœ°å€: https://github.com/666OS/YYDS
# ç‰ˆæœ¬: v6.1.0_Lite_1
# ä½œè€…: YYDS666
# æ›´æ–°: 2026 å¹´ 1 æœˆ 6 æ—¥
# é¢‘é“: https://t.me/Pinched666
# ==================== é”šç‚¹é…ç½® ====================
# ä»£ç†æä¾›è€…æ¨¡æ¿ - è®¢é˜…æºåŸºç¡€é…ç½®
BaseProvider: &BaseProvider {type: http, interval: 86400, proxy: DIRECT, health-check: {enable: true, url: 'https://www.google.com/generate_204', interval: 300}, filter: '^(?!.*(ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªçŽ¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|èŽ·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜Ž|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))'}

# ç­–ç•¥ç»„ç±»åž‹æ¨¡æ¿
BaseFB: &BaseFB {type: fallback, interval: 200, lazy: true, url: 'https://www.google.com/generate_204'}
BaseCH: &BaseCH {type: load-balance, interval: 200, lazy: true, url: 'https://www.google.com/generate_204', strategy: consistent-hashing, hidden: true}
BaseCR: &BaseCR {type: load-balance, interval: 200, lazy: true, url: 'https://www.google.com/generate_204', strategy: round-robin, hidden: true}
BaseUT: &BaseUT {type: url-test, interval: 200, lazy: true, url: 'https://www.google.com/generate_204', hidden: true}

# èŠ‚ç‚¹ç­›é€‰æ­£åˆ™è¡¨è¾¾å¼ - ä»…ä¿ç•™å››å¤§é‡‘åˆš
FilterHK: &FilterHK '^(?=.*(?i)(æ¸¯|ðŸ‡­ðŸ‡°|HK|Hong|HKG))(?!.*(æŽ’é™¤1|æŽ’é™¤2|5x)).*$'
FilterSG: &FilterSG '^(?=.*(?i)(å¡|ðŸ‡¸ðŸ‡¬|SG|Sing|SIN|XSP))(?!.*(æŽ’é™¤1|æŽ’é™¤2|5x)).*$'
FilterJP: &FilterJP '^(?=.*(?i)(æ—¥|ðŸ‡¯ðŸ‡µ|JP|Japan|NRT|HND|KIX|CTS|FUK))(?!.*(æŽ’é™¤1|æŽ’é™¤2|5x)).*$'
FilterUS: &FilterUS '^(?=.*(?i)(ç¾Ž|ðŸ‡ºðŸ‡¸|US|USA|SJC|JFK|LAX|ORD|ATL|DFW|SFO|MIA|SEA|IAD))(?!.*(æŽ’é™¤1|æŽ’é™¤2|5x)).*$'
FilterAL: &FilterAL '^(?!.*(DIRECT|ç›´æŽ¥è¿žæŽ¥|ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªçŽ¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|èŽ·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜Ž|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))'

# ç­–ç•¥ç»„ä»£ç†åˆ—è¡¨æ¨¡æ¿ - ç§»é™¤å†—ä½™åœ°åŒº
SelectFB: &SelectFB {type: select, proxies: [æ•…éšœè½¬ç§», é¦™æ¸¯ç­–ç•¥, ç‹®åŸŽç­–ç•¥, æ—¥æœ¬ç­–ç•¥, ç¾Žå›½ç­–ç•¥, å…¨çƒæ‰‹åŠ¨, ç›´æŽ¥è¿žæŽ¥]}
SelectPY: &SelectPY {type: select, proxies: [é»˜è®¤ä»£ç†, æ•…éšœè½¬ç§», é¦™æ¸¯ç­–ç•¥, ç‹®åŸŽç­–ç•¥, æ—¥æœ¬ç­–ç•¥, ç¾Žå›½ç­–ç•¥, å…¨çƒæ‰‹åŠ¨, ç›´æŽ¥è¿žæŽ¥]}
SelectDC: &SelectDC {type: select, proxies: [ç›´æŽ¥è¿žæŽ¥, é»˜è®¤ä»£ç†, æ•…éšœè½¬ç§», é¦™æ¸¯ç­–ç•¥, ç‹®åŸŽç­–ç•¥, æ—¥æœ¬ç­–ç•¥, ç¾Žå›½ç­–ç•¥, å…¨çƒæ‰‹åŠ¨]}
SelectHK: &SelectHK {type: select, proxies: [é¦™æ¸¯ç­–ç•¥, é»˜è®¤ä»£ç†, æ•…éšœè½¬ç§», ç‹®åŸŽç­–ç•¥, æ—¥æœ¬ç­–ç•¥, ç¾Žå›½ç­–ç•¥, å…¨çƒæ‰‹åŠ¨, ç›´æŽ¥è¿žæŽ¥]}
SelectSG: &SelectSG {type: select, proxies: [ç‹®åŸŽç­–ç•¥, é»˜è®¤ä»£ç†, æ•…éšœè½¬ç§», é¦™æ¸¯ç­–ç•¥, æ—¥æœ¬ç­–ç•¥, ç¾Žå›½ç­–ç•¥, å…¨çƒæ‰‹åŠ¨, ç›´æŽ¥è¿žæŽ¥]}
SelectUS: &SelectUS {type: select, proxies: [ç¾Žå›½ç­–ç•¥, é»˜è®¤ä»£ç†, æ•…éšœè½¬ç§», é¦™æ¸¯ç­–ç•¥, ç‹®åŸŽç­–ç•¥, æ—¥æœ¬ç­–ç•¥, å…¨çƒæ‰‹åŠ¨, ç›´æŽ¥è¿žæŽ¥]}

# ==================== ä»£ç†æä¾›è€… ====================
proxy-providers:
  # è¯·åœ¨ä¸‹æ–¹ url å¤„å¡«å…¥ä½ çš„è®¢é˜…é“¾æŽ¥
  ä¼˜è´¨æœåŠ¡å•†: {<<: *BaseProvider, url: 'ä½ çš„æœºåœºè®¢é˜…é“¾æŽ¥', override: {additional-prefix: '[ä¼˜] '}}
  å¤‡ç”¨æœåŠ¡å•†: {<<: *BaseProvider, url: 'ä½ çš„å¤‡ç”¨è®¢é˜…é“¾æŽ¥', override: {additional-prefix: '[å¤‡] '}}

# ==================== æ ¸å¿ƒé…ç½® ====================
mode: rule
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: true
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: error
bind-address: '*'
find-process-mode: 'always'
global-client-fingerprint: chrome
keep-alive-interval: 15
keep-alive-idle: 600

authentication:
  - mihomo:yyds666
skip-auth-prefixes:
  - 192.168.1.0/24
  - 127.0.0.1/8

experimental:
  quic-go-disable-gso: true   
      
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
external-ui-name: zashboard
external-ui: ui
external-controller: 127.0.0.1:9090
secret: 123456

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

tun:
  enable: false
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
     
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fake-ip-filter:
    - rule-set:Direct
    - rule-set:Private
    - rule-set:China
    - +.miwifi.com
    - +.docker.io

# ==================== ä»£ç†ç­–ç•¥ç»„ ====================
proxy-groups:
  # ==================== ä¸»è¦ç­–ç•¥ç»„ ====================
  - {name: é»˜è®¤ä»£ç†,      <<: *SelectFB, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Static.png}
  - {name: æ•…éšœè½¬ç§»,      <<: *BaseFB, proxies: [é¦™æ¸¯ç­–ç•¥, ç‹®åŸŽç­–ç•¥, æ—¥æœ¬ç­–ç•¥, ç¾Žå›½ç­–ç•¥, å…¨çƒæ‰‹åŠ¨, ç›´æŽ¥è¿žæŽ¥], icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/ULB.png}
  - {name: å›½å¤–æµé‡,      <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Global.png}
  - {name: å›½å†…æµé‡,      <<: *SelectDC, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/China.png}
  - {name: å…œåº•æµé‡,      <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Final.png}
  - {name: ç›´æŽ¥è¿žæŽ¥,      type: select, proxies: [DIRECT], hidden: true, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Direct.png}

  # ==================== åŠŸèƒ½ç­–ç•¥ç»„ ====================
  - {name: ç½‘ç»œæµ‹è¯•,      <<: *SelectPY, include-all: true, filter: *FilterAL, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Speedtest.png}
  - {name: æŠ–å¿«ä¹¦å®šä½,    type: select, proxies: [ç›´æŽ¥è¿žæŽ¥, é¦™æ¸¯ç­–ç•¥, ç‹®åŸŽç­–ç•¥, æ—¥æœ¬ç­–ç•¥, ç¾Žå›½ç­–ç•¥], icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Null_Nation.png}

  # ==================== åª’ä½“æœåŠ¡ ====================
  - {name: Embyæœ,       <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Emby.png}
  - {name: æ²¹ç®¡è§†é¢‘,      <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/YouTube.png}
  - {name: å¥ˆé£žè§†é¢‘,      <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Netflix.png}
  - {name: å›½é™…åª’ä½“,      <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/DomesticMedia.png}
  - {name: æ–°é—»åª’ä½“,      <<: *SelectUS, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Apple_News.png}

  # ==================== ç¤¾äº¤å¹³å° ====================
  - {name: ç”µæŠ¥æ¶ˆæ¯,      <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Telegram_X.png}
  - {name: æŽ¨ç‰¹ç¤¾äº¤,      <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/X.png}
  - {name: ç¤¾äº¤å¹³å°,      <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/PBS.png}

  # ==================== å•†ä¸šæœåŠ¡ ====================
  - {name: äººå·¥æ™ºèƒ½,      <<: *SelectUS, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/AI.png}
  - {name: è´§å¸å¹³å°,      <<: *SelectSG, icon: https://raw.githubusercontent.com/Orz-3/mini/master/Alpha/Bitcloud.png}
  - {name: æ¸¸æˆå¹³å°,      <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Game.png}
  - {name: å¾®è½¯æœåŠ¡,      <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Microsoft.png}
  - {name: è°·æ­ŒæœåŠ¡,      <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Google_Search.png}
  - {name: è‹¹æžœæœåŠ¡,      <<: *SelectPY, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Apple.png}

  # ==================== åœ°åŒºç­–ç•¥ç»„ ====================
  - {name: é¦™æ¸¯ç­–ç•¥,      type: select, proxies: [é¦™æ¸¯è‡ªåŠ¨, é¦™æ¸¯å‡è¡¡-æ•£åˆ—, é¦™æ¸¯å‡è¡¡-è½®è¯¢], include-all: true, filter: *FilterHK, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Hong_Kong.png}
  - {name: ç‹®åŸŽç­–ç•¥,      type: select, proxies: [ç‹®åŸŽè‡ªåŠ¨, ç‹®åŸŽå‡è¡¡-æ•£åˆ—, ç‹®åŸŽå‡è¡¡-è½®è¯¢], include-all: true, filter: *FilterSG, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Singapore.png}
  - {name: æ—¥æœ¬ç­–ç•¥,      type: select, proxies: [æ—¥æœ¬è‡ªåŠ¨, æ—¥æœ¬å‡è¡¡-æ•£åˆ—, æ—¥æœ¬å‡è¡¡-è½®è¯¢], include-all: true, filter: *FilterJP, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Japan.png}
  - {name: ç¾Žå›½ç­–ç•¥,      type: select, proxies: [ç¾Žå›½è‡ªåŠ¨, ç¾Žå›½å‡è¡¡-æ•£åˆ—, ç¾Žå›½å‡è¡¡-è½®è¯¢], include-all: true, filter: *FilterUS, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/United_States.png}

  # ==================== å…¶ä»–ç­–ç•¥ç»„ ====================
  - {name: å…¨çƒæ‰‹åŠ¨,      type: select, include-all: true, filter: *FilterAL, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Clubhouse.png}

  # ==================== è‡ªåŠ¨æµ‹é€Ÿç»„ ====================
  - {name: é¦™æ¸¯è‡ªåŠ¨,      <<: *BaseUT, include-all: true, filter: *FilterHK, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Auto.png}
  - {name: ç‹®åŸŽè‡ªåŠ¨,      <<: *BaseUT, include-all: true, filter: *FilterSG, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Auto.png}
  - {name: æ—¥æœ¬è‡ªåŠ¨,      <<: *BaseUT, include-all: true, filter: *FilterJP, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Auto.png}
  - {name: ç¾Žå›½è‡ªåŠ¨,      <<: *BaseUT, include-all: true, filter: *FilterUS, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Auto.png}

  # ==================== è´Ÿè½½å‡è¡¡-æ•£åˆ— ====================
  - {name: é¦™æ¸¯å‡è¡¡-æ•£åˆ—, <<: *BaseCH, include-all: true, filter: *FilterHK, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Round_Robin_1.png}
  - {name: ç‹®åŸŽå‡è¡¡-æ•£åˆ—, <<: *BaseCH, include-all: true, filter: *FilterSG, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Round_Robin_1.png}
  - {name: æ—¥æœ¬å‡è¡¡-æ•£åˆ—, <<: *BaseCH, include-all: true, filter: *FilterJP, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Round_Robin_1.png}
  - {name: ç¾Žå›½å‡è¡¡-æ•£åˆ—, <<: *BaseCH, include-all: true, filter: *FilterUS, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Round_Robin_1.png}

  # ==================== è´Ÿè½½å‡è¡¡-è½®è¯¢ ====================
  - {name: é¦™æ¸¯å‡è¡¡-è½®è¯¢, <<: *BaseCR, include-all: true, filter: *FilterHK, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Round_Robin.png}
  - {name: ç‹®åŸŽå‡è¡¡-è½®è¯¢, <<: *BaseCR, include-all: true, filter: *FilterSG, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Round_Robin.png}
  - {name: æ—¥æœ¬å‡è¡¡-è½®è¯¢, <<: *BaseCR, include-all: true, filter: *FilterJP, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Round_Robin.png}
  - {name: ç¾Žå›½å‡è¡¡-è½®è¯¢, <<: *BaseCR, include-all: true, filter: *FilterUS, icon: https://git.imee.me/https://github.com/Koolson/Qure/raw/master/IconSet/Color/Round_Robin.png}

# ==================== è§„åˆ™è·¯ç”± ====================
rules: 
  # AIä¼˜å…ˆ
  - RULE-SET,AI,äººå·¥æ™ºèƒ½
  - RULE-SET,AIIP,äººå·¥æ™ºèƒ½,no-resolve
  
  # æ‹¦æˆªè§„åˆ™
  - RULE-SET,Tracking,REJECT
  - RULE-SET,Advertising,REJECT
  - AND,((DST-PORT,443),(NETWORK,UDP)),REJECT  # é˜»æ­¢ QUIC

  # åŸŸåè§„åˆ™
  - RULE-SET,LocationDKS,æŠ–å¿«ä¹¦å®šä½
  - RULE-SET,Private,ç›´æŽ¥è¿žæŽ¥
  - RULE-SET,Direct,ç›´æŽ¥è¿žæŽ¥
  - RULE-SET,XPTV,ç›´æŽ¥è¿žæŽ¥
  - RULE-SET,Download,ç›´æŽ¥è¿žæŽ¥
  - RULE-SET,AppleCN,ç›´æŽ¥è¿žæŽ¥
  - DOMAIN-KEYWORD,speedtest,ç½‘ç»œæµ‹è¯•
  - RULE-SET,Speedtest,ç½‘ç»œæµ‹è¯•
  - RULE-SET,Twitter,æŽ¨ç‰¹ç¤¾äº¤
  - RULE-SET,Telegram,ç”µæŠ¥æ¶ˆæ¯
  - RULE-SET,SocialMedia,ç¤¾äº¤å¹³å°
  - RULE-SET,NewsMedia,æ–°é—»åª’ä½“
  - RULE-SET,Games,æ¸¸æˆå¹³å°
  - RULE-SET,Crypto,è´§å¸å¹³å°
  - RULE-SET,Emby,Embyæœ
  - RULE-SET,Netflix,å¥ˆé£žè§†é¢‘
  - RULE-SET,YouTube,æ²¹ç®¡è§†é¢‘
  - RULE-SET,Streaming,å›½é™…åª’ä½“
  - RULE-SET,Apple,è‹¹æžœæœåŠ¡ 
  - RULE-SET,Google,è°·æ­ŒæœåŠ¡
  - RULE-SET,Microsoft,å¾®è½¯æœåŠ¡
  - RULE-SET,Proxy,å›½å¤–æµé‡
  - RULE-SET,China,å›½å†…æµé‡

  # IPè§„åˆ™
  - RULE-SET,AdvertisingIP,REJECT,no-resolve
  - RULE-SET,PrivateIP,ç›´æŽ¥è¿žæŽ¥,no-resolve
  - RULE-SET,XPTVIP,ç›´æŽ¥è¿žæŽ¥,no-resolve
  - RULE-SET,TelegramIP,ç”µæŠ¥æ¶ˆæ¯,no-resolve
  - RULE-SET,SocialMediaIP,ç¤¾äº¤å¹³å°,no-resolve
  - RULE-SET,EmbyIP,Embyæœ,no-resolve
  - RULE-SET,NetflixIP,å¥ˆé£žè§†é¢‘,no-resolve
  - RULE-SET,StreamingIP,å›½é™…åª’ä½“,no-resolve
  - RULE-SET,GoogleIP,è°·æ­ŒæœåŠ¡,no-resolve
  - RULE-SET,ProxyIP,å›½å¤–æµé‡,no-resolve
  - RULE-SET,ChinaIP,å›½å†…æµé‡,no-resolve

  # å…œåº•è§„åˆ™
  - MATCH,å…œåº•æµé‡

# ==================== è§„åˆ™é›† ====================
# è§„åˆ™é›†è¡Œä¸ºæ¨¡æ¿
BehaviorDN: &BehaviorDN {type: http, behavior: domain, format: mrs, interval: 86400}
BehaviorIP: &BehaviorIP {type: http, behavior: ipcidr, format: mrs, interval: 86400}

# è§„åˆ™æä¾›è€…
rule-providers:  
  # åŸŸåè§„åˆ™
  Tracking:       {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Tracking.mrs}
  Advertising:    {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Advertising.mrs} 
  Direct:         {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Direct.mrs}
  LocationDKS:    {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/LocationDKS.mrs}
  Private:        {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Private.mrs}
  Download:       {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Download.mrs}
  Speedtest:      {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Speedtest.mrs}
  AI:             {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/AI.mrs}  
  Telegram:       {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Telegram.mrs}
  Twitter:        {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Twitter.mrs}  
  SocialMedia:    {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/SocialMedia.mrs}
  NewsMedia:      {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/NewsMedia.mrs}
  Games:          {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Games.mrs}
  Crypto:         {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Crypto.mrs}
  Netflix:        {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Netflix.mrs}
  YouTube:        {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/YouTube.mrs}
  XPTV:           {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/XPTV.mrs}  
  Emby:           {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Emby.mrs}
  Streaming:      {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Streaming.mrs}  
  AppleCN:        {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/AppleCN.mrs}
  Apple:          {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Apple.mrs}
  Google:         {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Google.mrs}
  Microsoft:      {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Microsoft.mrs}  
  Facebook:       {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Facebook.mrs}
  Proxy:          {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/Proxy.mrs}
  China:          {<<: *BehaviorDN, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/domain/China.mrs}

  # IPè§„åˆ™
  AdvertisingIP:  {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/Advertising.mrs}
  PrivateIP:      {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/Private.mrs}
  AIIP:           {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/AI.mrs}
  TelegramIP:     {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/Telegram.mrs}  
  SocialMediaIP:  {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/SocialMedia.mrs}  
  XPTVIP:         {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/XPTV.mrs}
  EmbyIP:         {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/Emby.mrs}
  NetflixIP:      {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/Netflix.mrs}
  StreamingIP:    {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/Streaming.mrs}  
  GoogleIP:       {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/Google.mrs}
  FacebookIP:     {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/Facebook.mrs}  
  ProxyIP:        {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/Proxy.mrs} 
  ChinaIP:        {<<: *BehaviorIP, url: https://git.imee.me/https://github.com/666OS/rules/raw/release/mihomo/ip/China.mrs}
# ==================== EOF ====================
